RoomReservation/Controllers/CalendarsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.ProjectModel;
using RoomReservation.Data;
using RoomReservation.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace RoomReservation.Controllers
{
	[Authorize]
	public class CalendarsController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ApplicationDbContext _context;

		public CalendarsController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
		{
			_userManager = userManager;
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			var rooms = await _context.Rooms.ToListAsync();
			rooms.OrderBy(x => x.Name);

			return View(rooms);
		}

		public async Task<IActionResult> ViewCalendar(string id)
		{
			var connectedUser = await _userManager.FindByNameAsync(User.Identity.Name);
			var room = await _context.Rooms.FindAsync(id);

			var reservations = await _context.Reservations.Where(x => x.ReservedRoom.Id == id).Include(r => r.ReservingUser).ToListAsync();

			var reservationsVM = new List<ReservationViewModel>();

			foreach(var r in reservations)
			{
				ReservationViewModel viewModel = new ReservationViewModel
				{
					Id = r.Id,
					StartingTime = r.StartingTime,
					EndingTime = r.EndingTime,
					Title = $"{r.ReservingUser.FirstName} {r.ReservingUser.LastName}",
					Editable = r.ReservingUser.Id == connectedUser.Id || User.IsInRole("Admin") ? true : false,
					DurationEditable = r.ReservingUser.Id == connectedUser.Id || User.IsInRole("Admin") ? true : false,
					Overlap = false
				};

				reservationsVM.Add(viewModel);
			}

			var calendarVM = new CalendarViewModel();

			calendarVM.Room = room;
			calendarVM.JSONData = JsonSerializer.Serialize(reservationsVM, new JsonSerializerOptions { WriteIndented = true});

			return View(calendarVM);
		}
	}
}

RoomReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoomReservation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Room Reservation System Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link btn btn-primary text-light" asp-area="" asp-controller="Calendars" asp-action="Index">New booking</a>
                            </li>
                            @if (User.IsInRole(RoomReservation.Enums.Roles.Admin.ToString()))
                            {
                                <li class="nav-item">
                                    <div class="btn-group">
                                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administration</button>
                                        <div class="dropdown-menu shadow">
                                            <a class="dropdown-item" asp-controller="rooms" asp-action="index">Rooms</a>
                                            <a class="dropdown-item" asp-controller="users" asp-action="index">Users</a>
                                        </div>
                                    </div>
                                </li>
                            }
                         }
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Guillaume Fontorbe</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>