RoomReservation/Models/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomReservation.Models
{
	public class CalendarViewModel
	{
		public string JSONData { get; set; }
		public Reservation ReservationToCreate { get; set; }
		public Reservation ReservationToEdit { get; set; }
		public Room Room { get; set; }
	}
}

RoomReservation/Controllers/CalendarsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.ProjectModel;
using RoomReservation.Data;
using RoomReservation.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace RoomReservation.Controllers
{
	[Authorize]
	public class CalendarsController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ApplicationDbContext _context;

		public CalendarsController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
		{
			_userManager = userManager;
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			var rooms = await _context.Rooms.ToListAsync();
			rooms.OrderBy(x => x.Name);

			return View(rooms);
		}

		public async Task<IActionResult> ViewCalendar(string id)
		{
			var connectedUser = await _userManager.FindByNameAsync(User.Identity.Name);
			var room = await _context.Rooms.FindAsync(id);

			var reservations = await _context.Reservations.Where(x => x.ReservedRoom.Id == id).Include(r => r.ReservingUser).ToListAsync();

			var reservationsVM = new List<ReservationViewModel>();

			foreach(var r in reservations)
			{
				ReservationViewModel viewModel = new ReservationViewModel
				{
					Id = r.Id,
					StartingTime = r.StartingTime,
					EndingTime = r.EndingTime,
					Title = $"{r.ReservingUser.FirstName} {r.ReservingUser.LastName}",
					Editable = r.ReservingUser.Id == connectedUser.Id || User.IsInRole("Admin") ? true : false,
					DurationEditable = r.ReservingUser.Id == connectedUser.Id || User.IsInRole("Admin") ? true : false,
					Overlap = false
				};

				reservationsVM.Add(viewModel);
			}

			var calendarVM = new CalendarViewModel();

			calendarVM.Room = room;
			calendarVM.JSONData = JsonSerializer.Serialize(reservationsVM, new JsonSerializerOptions { WriteIndented = true});

			return View(calendarVM);
		}
	}
}

RoomReservation/Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoomReservation.Data;
using RoomReservation.Data.Repositories;
using RoomReservation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace RoomReservation.Controllers
{
	public class ReservationsController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly IReservationRepository _repository;

		public ReservationsController(UserManager<ApplicationUser> userManager, IReservationRepository repository)
		{
			_userManager = userManager;
			_repository = repository;
		}

		public async Task<IActionResult> Create(CalendarViewModel calendarViewModel)
		{
			if (ModelState.IsValid)
			{
				Reservation reservation = new Reservation();

				reservation.StartingTime = calendarViewModel.ReservationToCreate.StartingTime;
				reservation.EndingTime = calendarViewModel.ReservationToCreate.EndingTime;
				reservation.ReservedRoom = await _repository.GetRoomById(calendarViewModel.Room.Id);
				reservation.ReservingUser = await _userManager.FindByNameAsync(User.Identity.Name);

                await _repository.AddAsync(reservation);
				
				return RedirectToRoute("return",routeValues: new {controller= "Calendars", action="ViewCalendar", id = reservation.ReservedRoom.Id });
			}
			return RedirectToRoute("return", routeValues: new { controller = "Calendars", action = "ViewCalendar", id = calendarViewModel.Room.Id });
		}

		public async Task<IActionResult> Edit(CalendarViewModel calendarViewModel)
		{
			// TODO:add check that the user is the correct one or is the admin (to avoid override by http request)
			var reservationInDb = await _repository.GetByIdAsync(calendarViewModel.ReservationToEdit.Id);

			if(reservationInDb.StartingTime != calendarViewModel.ReservationToEdit.StartingTime || reservationInDb.EndingTime != calendarViewModel.ReservationToEdit.EndingTime)
			{
				reservationInDb.StartingTime = calendarViewModel.ReservationToEdit.StartingTime;
				reservationInDb.EndingTime = calendarViewModel.ReservationToEdit.EndingTime;

				await _repository.UpdateAsync(reservationInDb);
			}

			return RedirectToRoute("return", routeValues: new { controller = "Calendars", action = "ViewCalendar", id = calendarViewModel.Room.Id });
		}

		[HttpPost]
		public async Task<IActionResult> Delete(string id)
		{
			// TODO:add check that the user is the correct one or is the admin (to avoid override by http request)

			var reservationToDelete = await _repository.GetByIdAsync(id);

			await _repository.DeleteAsync(reservationToDelete);

			return RedirectToRoute("return", routeValues: new { controller = "Calendars", action = "ViewCalendar", id = reservationToDelete.ReservedRoom.Id });
		}
	}
}

RoomReservation/Views/Calendars/Index.cshtml
@model IEnumerable<RoomReservation.Models.Room>

    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <p>To access the reservation system, click on the "View Calendar" button for the chosen room.</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="ViewCalendar" asp-route-id="@item.Id" class="btn btn-primary">View calendar</a>
            </td>
        </tr>
}
    </tbody>
</table>

RoomReservation/Views/Calendars/ViewCalendar.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@model CalendarViewModel

@{
    ViewData["Title"] = "Calendar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-info alert-dismissible fade show" role="alert">
    <p>You can create a new reservation by clicking on a blank space in the calendar.</p>
    <p>If you click on a reservation made by yourself, you can edit or delete it.</p>
    <p>Only admins can edit and delete reservations made by others.</p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css">
<h1>Calendar for @Model.Room.Name</h1>
<div id="calendar"></div>



<div class="modal fade" tabindex="-1" role="dialog" id="CreateFormModal">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="CreateForm">
                <form asp-controller="Reservations" asp-action="Create">
                    <div class="modal-header">
                        <h5 class="modal-title">New booking</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <input asp-for="@Model.Room.Id" class="form-control" value="@Model.Room.Id" type="hidden" />
                        </div>
                        <div class="form-group">
                            <input asp-for="@Model.Room.Name" class="form-control" value="@Model.Room.Name" type="hidden" />
                        </div>
                        <div class="form-group">
                            <input asp-for="@Model.Room.Location" class="form-control" value="@Model.Room.Location" type="hidden" />
                        </div>
                        <div class="form-group">
                            <input asp-for="@Model.Room.Description" class="form-control" value="@Model.Room.Description" type="hidden" />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReservationToCreate.StartingTime" class="control-label"></label>
                            <input asp-for="@Model.ReservationToCreate.StartingTime" class="form-control" value="@DateTime.Now.ToString("s")" id="CreateFormStartingTime" />
                            <span asp-validation-for="@Model.ReservationToCreate.StartingTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ReservationToCreate.EndingTime" class="control-label"></label>
                            <input asp-for="ReservationToCreate.EndingTime" class="form-control" value="@DateTime.Now.AddHours(1).ToString("s")" id="CreateFormEndingTime" />
                            <span asp-validation-for="ReservationToCreate.EndingTime" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="EditFormModal">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="EditForm">
                <form asp-controller="Reservations" asp-action="Edit">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit booking</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group invisible">
                            <input asp-for="@Model.ReservationToEdit.Id" class="form-control" type="hidden" id="EditFormId" />
                        </div>
                        <div class="form-group invisible">
                            <input asp-for="@Model.Room.Id" class="form-control" value="@Model.Room.Id" type="hidden" />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReservationToEdit.StartingTime" class="control-label"></label>
                            <input asp-for="@Model.ReservationToEdit.StartingTime" class="form-control" id="EditFormStartingTime" />
                            <span asp-validation-for="@Model.ReservationToEdit.StartingTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReservationToEdit.EndingTime" class="control-label"></label>
                            <input asp-for="@Model.ReservationToEdit.EndingTime" class="form-control" id="EditFormEndingTime" />
                            <span asp-validation-for="@Model.ReservationToEdit.EndingTime" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" value="Edit" class="btn btn-info" />
                            <input type="button" value="Delete" class="btn btn-danger" onclick="deleteEvent()" />
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="DetailFormModal">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="EditForm">
                <form asp-controller="Reservations" asp-action="Edit">
                    <div class="modal-header">
                        <h5 class="modal-title">Booking details</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Reserving user</label>
                            <input class="form-control " id="DetailFormUser" disabled />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReservationToEdit.StartingTime" class="control-label"></label>
                            <input type="datetime-local" class="form-control" id="DetailFormStartingTime" disabled />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReservationToEdit.EndingTime" class="control-label"></label>
                            <input type="datetime-local" class="form-control" id="DetailFormEndingTime" disabled />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    var rootUrl = @Json.Serialize(@Configuration.GetSection("Routing").GetSection("Root").Value);

    var createForm = document.getElementById("CreateForm");
    var createFormStartingTime = document.getElementById("CreateFormStartingTime");
    var createFormEndingTime = document.getElementById("CreateFormEndingTime");

    var editFormId = document.getElementById("EditFormId");
    var editFormStartingTime = document.getElementById("EditFormStartingTime");
    var editFormEndingTime = document.getElementById("EditFormEndingTime");

    var detailFormUser = document.getElementById("DetailFormUser");
    var detailFormStartingTime = document.getElementById("DetailFormStartingTime");
    var detailFormEndingTime = document.getElementById("DetailFormEndingTime");

    document.addEventListener('DOMContentLoaded', function () {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            /*Sets the header toolbar*/
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },

            /*Configure interaction when clicking on a date*/
            dateClick: function (info) { toggleCreateForm(info);},

            /*Configure interaction when clicking on an event*/
            eventClick: function (info) { toggleEditForm(info);},

            /* Display events */
            events: @Html.Raw(Model.JSONData)
        });

        calendar.render();
    });

    function toggleCreateForm(info) {
        $("#CreateFormModal").modal('toggle');

        createFormStartingTime.setAttribute('value', info.dateStr + "T08:00:00");
        createFormEndingTime.setAttribute('value', info.dateStr + "T17:00:00");
    };

    function toggleEditForm(info) {

        if (info.event.startEditable == true) {
            $("#EditFormModal").modal('toggle');

            editFormId.setAttribute('value', info.event.id);
            editFormStartingTime.setAttribute('value', info.event.startStr.substring(0,info.event.startStr.length-6));
            editFormEndingTime.setAttribute('value', info.event.endStr.substring(0, info.event.endStr.length - 6));
        }
        else{
            $("#DetailFormModal").modal('toggle');

            detailFormUser.setAttribute('value', info.event.title);
            detailFormStartingTime.setAttribute('value', info.event.startStr.substring(0, info.event.startStr.length - 6));
            detailFormEndingTime.setAttribute('value', info.event.endStr.substring(0, info.event.endStr.length - 6));
        }

    }

    async function deleteEvent() {
        var eventId = $("#EditFormId").val().toString();

        console.log($("#EditFormId").val());

        await $.post("/Reservations/Delete", { id: eventId });

        location.reload();
    }

</script>